Update pg_kgdiff1.py
Fix:

ERROR:  unsupported Unicode escape sequence
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: {"magic": "KGDIFF1\u0000...
while creating return value
PL/Python function "kg_info"